<?php

namespace PhpClickHouseLaravel;

use ClickHouseDB\Transport\CurlerRequest;

class CurlerRollingWithRetries extends \ClickHouseDB\Transport\CurlerRolling
{

    protected $retries = 0;

    public function execOne(CurlerRequest $request, $auto_close = false)
    {
        return parent::execOne($request, $auto_close); // TODO: Change the autogenerated stub
    }
}
